### ISSUE TITLE
Allow providing secrets as paths

### ISSUE THREAD

**Issue by luckysori** [aidalgol/valheim-server-flake#16]
I've been using `sops-nix` to manage my secrets, but I cannot use the same pattern with this flake, since all the configuration values that I would like to keep secret (`serverName`, `password`, `permittedList`, `adminList`) must be specified directly.

It would be great if we could specify all of these values indirectly, either through environment variables or using file paths.

**Comment by aidalgol** [comment]
The only piece of information that really needs to be kept secret is the server password, and upstream makes this impossible by only taking this as a commandline argument (unless there is some undocumented way of putting it in a configuration file).

**Comment by luckysori** [comment]
Fair enough. Could we use a `.env` file instead? I've seen this pattern used for a flake like `restic`.

> The only piece of information that really needs to be kept secret is the server password

You are right, although it couldn't hurt to be able to keep the name of the server and player lists private too. Less important obviously.

**Comment by luckysori** [comment]
Okay, I think I found a way that doesn't require any changes here: https://github.com/pborzenkov/nix-config/blob/09c522c49baca298211eb7414ef5cd3025abe474/nixos/machines/rock/valheim.nix#L2.

Thank you! I'll close this now.
