### ISSUE TITLE
Encountered 401 on rebuild

### ISSUE THREAD

**Issue by PrestonStorm** [aidalgol/valheim-server-flake#18]
Hello,

I am getting an error on rebuild with this flake. Here is the output of the error:
```
No username given. Using anonymous account with dedicated server subscription.
Connecting to Steam3... Done!
Logging anonymously into Steam3... Done!
Using Steam3 suggested CellID: 79
Got AppInfo for 896660
Using app branch: 'public'.
Got depot key for 896661 result: OK
Processing depot 896661
Downloading depot manifest... Got manifest request code for 896661 2352546016341516446 result: 0
No manifest request code was returned for 896661 2352546016341516446
Encountered 401 for depot manifest 896661 2352546016341516446. Aborting.

Unable to download manifest 2352546016341516446 for depot 896661
App 896660 was not completely downloaded.
The operation was canceled.
Disconnected from Steam
```

I don't know what is important information so please ask if I should send something. My flake is on unstable and when I updated my flake.lock file I get this error. For now I can revert to an old version of the lock file and still rebuild fine but I thought flakes kept this kind of thing from happening. (still a noob here)

Any Ideas?

**Comment by PrestonStorm** [comment]
Okay I correct myself. If you look at [this search](https://github.com/SteamRE/DepotDownloader/issues?q=is%3Aissue+is%3Aclosed+401), you can see that a 401 error with the DeoptDownloader is fairly common and usually indicates that the specific manifest has been removed. It is nothing to do with me being on unstable, just that when I updated it tries to update the Valheim server to the manifest ID in the latest update, apparently the manifest ID here is not available anymore.

I don't know why they aren't available anymore, perhaps someone knows? Seems like they should keep old versions but I'll leave that be...

I forked and updated to what was listed as latest public and it builds fine. I'll submit a pull request.

**Comment by aidalgol** [comment]
Sounds like publishers are allowed to remove depots.  Closing in favour of #19.
